My\TrainingBundle\Entity\Job:
  properties:
    category:
      - NotBlank: ~
    type:
      - NotBlank: ~
      - Choice: {callback: getTypeValues}
    company:
      - NotBlank: ~
    position:
      - NotBlank: ~
    location:
      - NotBlank: ~
    description:
      - NotBlank: ~
    how_to_apply:
      - NotBlank: ~
    token:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email:
          message: The email "{{ value }}" is not valid.
